config/routes.rb
Rails.application.routes.draw do
  localized do
    #get '/index', to: 'app/front#index', as: :app_index
  end

  root to: 'app/front#index'
  get '/about', to: 'app/front#about', as: :app_about
  get '/form', to: 'app/front#form', as: :app_form

  devise_for :users, skip: KepplerConfiguration.skip_module_devise
  post '/filter', to: 'admin/users#filter_by_role', as: :filter_by_role

  namespace :admin do
    root to: 'admin#root'

    namespace :rockets do
      get '/', action: :rockets
      post 'create/:rocket', action: :create, as: :create
      post 'install', action: :install
      post 'build/:rocket', action: :build, as: :build
      delete 'uninstall/:rocket', action: :uninstall, as: :uninstall
    end

    get '/seo/sitemap', to: 'seos#sitemap'
    get '/seo/robots', to: 'seos#robots'
    post '/seo/editor/save', to: 'seos#editor_save'

    resources :seos do
      post '/sort', action: :sort, on: :collection
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      post '/upload', action: 'upload', as: :upload
      get(
        '/reload',
        action: :reload,
        on: :collection,
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :roles do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      post '/upload', action: 'upload', as: :upload
      get '/download', action: 'download', as: :download
      post(
        '/sort',
        action: :sort,
        on: :collection,
      )
      get(
        '/reload',
        action: :reload,
        on: :collection,
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
      # post '/show_description/:module/:action_name', action: 'show_description', as: :show_description
      # get(
      #   '/add_permissions',
      #   action: 'add_permissions',
      #   as: :add_permissions
      # )
      # post(
      #   '/create_permissions',
      #   action: 'create_permissions',
      #   as: :create_permissions
      # )
    end

    scope :roles do
      post(
        ':role_id/show_description/:module/:action_name',
        to: 'permissions#show',
        as: :role_show_description
      )
      get(
        ':role_id/add_permissions',
        to: 'permissions#add',
        as: :role_add_permissions
      )
      post(
        ':role_id/create_permissions',
        to: 'permissions#create',
        as: :role_create_permissions
      )
      post(
        ':role_id/toggle_permissions',
        to: 'permissions#toggle_permissions',
        as: :role_toggle_permissions
      )
    end

    resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/delete_avatar', action: :delete_avatar
      get(
        '/reload',
        action: :reload,
        on: :collection
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :meta_tags do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      post '/upload', action: 'upload', as: :upload
      post(
        '/sort',
        action: :sort,
        on: :collection,
      )
      get(
        '/reload',
        action: :reload,
        on: :collection,
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :scripts do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      post '/upload', action: 'upload', as: :upload
      post(
        '/sort',
        action: :sort,
        on: :collection,
      )
      get(
        '/reload',
        action: :reload,
        on: :collection,
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :settings, only: [] do
      collection do
        post '/lang/:locale', to: 'settings#change_locale', as: :change_locale
        get '/:config', to: 'settings#edit', as: ''
        put '/:config', to: 'settings#update', as: 'update'
        put '/:config/appearance_default', to: 'settings#appearance_default', as: 'appearance_default'
      end
    end
  end

  # Errors routes
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Dashboard routes engine
  mount KepplerGaDashboard::Engine, at: 'admin/dashboard', as: 'dashboard'

  # Frontend routes engine
  mount KepplerFrontend::Engine, at: '/', as: 'frontend'

  # Language routes engine
  mount KepplerLanguages::Engine, at: '/', as: 'languages'

  # Capsules routes engine
  mount KepplerCapsules::Engine, at: '/', as: 'capsules'

  # Ckeditor routes engine
  mount Ckeditor::Engine => '/ckeditor'

  # KepplerContactUs routes engine
  mount KepplerContactUs::Engine, at: '/', as: 'keppler_contact_us'

  # Customers routes engine
  mount KepplerCustomers::Engine, at: '/', as: 'customers'

  # Banners routes engine
  mount KepplerBanners::Engine, at: '/', as: 'banners' 
end

app/models/permission.rb
# frozen_string_literal: true

# Permission
class Permission < ApplicationRecord
  belongs_to :role
end

app/controllers/admin/permissions_controller.rb
# frozen_string_literal: true

module Admin
  # PermissionsController
  class PermissionsController < AdminController
    before_action :set_role

    def add; end

    def create
      @module = params[:role][:module]
      @action = params[:role][:action]
      @actions = params[:role][:actions]

      if @role.permissions?
        @role.toggle_actions(@module, @action)
      else
        @role.first_permission(@module, @action)
      end
    end

    def show
      @module = params[:module]
      @action = params[:action_name]
    end

    def toggle_permissions
      @module = params[:role][:module]
      all_actions = params[:role][:actions]
      if @role.permissions?
        add_actions_or_module(@module, all_actions)
      else
        @actions = all_actions
        @role.first_permission(@module, @actions)
      end
    end

    private

    def add_actions_or_module(module_name, actions)
      if @role.permission_to(module_name)
        @actions = (actions - @role.all_permissions[module_name]['actions'])
        @role.toggle_all_actions(module_name, actions)
      else
        @role.add_module(module_name, actions)
      end

      @actions = actions if @actions.blank?
    end

    def set_role
      @role = Role.find(params[:role_id])
    end
  end
end

app/views/admin/permissions/_switch.html.haml
= simple_form_for role, url: admin_role_toggle_permissions_path(role), method: :post, remote: true do
  %label.switch-box{ style: 'padding-top: 5px; padding-right: 0px' }
    %label.switch
      %input{ name: 'role[module]', type: 'hidden', value: module_name }
      - actions.each do |action|
        %input{ name: 'role[actions][]', type: 'hidden', value: action }
      %input{ id: "all-#{module_name.split('::').join('')}", type: 'checkbox', class: ('active' if role.all_actions?(module_name, actions)) }
      %span.slider.round{ onclick: "send('#{module_name}', '#{actions}')" }

:javascript
  function send(module_name, actions) {
    $('#all-'+module_name.split('::').join('')).parent().parent().parent().submit()
  }

app/views/admin/permissions/add.html.haml
.container
  .row
    .col-lg-2
      = link_to admin_roles_path, 'data-position' => 'bottom', 'data-tooltip' => t('keppler.actions.back') do
        .arrow-back.btn.btn-default
          %i.icon-arrow-left
          = t('keppler.actions.back')
  .row
    .col-lg-12
      %section.content-header.index-header
        %h1{ style: 'display: inline-block; margin-left: 15px' }
          Role:
          = @role.name
    .col-lg-6
      - @modules&.each do |module_name|
        - module_name&.each do |key|
          - unless module_name[key.first]['name'].eql?('dashboard')
            .col-lg-12
              .box.slice-box.collapsed-box
                .box-header.with-border
                  .pull-left
                    %h4.box-title= t("keppler.sidebar-menu.#{module_name[key.first]['name'].downcase}")
                  .box-tools
                    .pull-left
                      .switch-div{ id: "switch-container-#{module_name[key.first]['model']}" }
                        = render 'admin/permissions/switch', role: @role, module_name: module_name[key.first]['model'], actions: module_name[key.first]['actions']
                    .pull-right
                      %a.btn.btn-box-tool{ 'data-widget' => 'collapse', type: 'button' }
                        %i.fa.fa-plus
                .box-body{ style: 'padding: 0 !important' }
                  %table.table
                    %tbody
                      - module_name[key.first]['actions'].each do |action|
                        %tr
                          %td.row-selectable.table-data
                            = link_to admin_role_show_description_path(@role, module_name[key.first]['name'].split('::').join(''), action), method: :post, remote: true do
                              .pull-left
                                %span= t("keppler.permissions.#{action}")
                              .pull-right.switch-div
                                = render 'admin/roles/switch', role: @role, module_name: module_name[key.first]['model'], action: action, actions: module_name[key.first]['actions']


                  - module_name&.dig(key.first, 'childrens')&.each do |children|
                    - children.each do |ky|
                      .box.slice-box.collapsed-box{ style: 'padding-right: 0 !important' }
                        .box-header.with-border
                          %h4.box-title= t("keppler.sidebar-menu.#{children[ky.first]['name'].parameterize.pluralize}")
                          .box-tools
                            .pull-left
                              .switch-div{ id: "switch-container-#{children[ky.first]['model']}" }
                                = render 'admin/permissions/switch', role: @role, module_name: children[ky.first]['model'], actions: children[ky.first]['actions']
                            .pull-right
                              %a.btn.btn-box-tool{ 'data-widget' => 'collapse', type: 'button' }
                                %i.fa.fa-plus
                        .box-body{ style: 'padding: 0 !important' }
                          %table.table.table-bordered
                            %tbody
                              - children[ky.first]['actions'].each do |action|
                                %tr
                                  %td.row-selectable.table-data{ style: 'padding-left: 20px' }
                                    = link_to admin_role_show_description_path(@role, children[ky.first]['model'].split('::').join(''), action), method: :post, remote: true do
                                      .pull-left
                                        %h4= t("keppler.permissions.#{action}")
                                      .pull-right.switch-div
                                        = render 'admin/roles/switch', role: @role, module_name: children[ky.first]['model'], action: action, actions: children[ky.first]['actions']

    .col-lg-6.hidden-xs
      %div{ style: 'width: 43%; height: 100%; position: fixed; right: 0px' }
        .col-lg-12
          .box.slice-box
            .box-header.with-border
              %h4.box-title= t('activerecord.attributes.description')

            .box-body
              %table.table.table-bordered
                %tbody
                  #description-list
                    - @modules.each do |module_name|
                      - module_name.each do |key|
                        - unless module_name[key.first]['name'].eql?('dashboard')
                          - module_name[key.first]['actions'].each do |action|
                            .no-visible{ id: "description-#{module_name[key.first]['name'].split('::').join('')}-#{action}" }
                              %h5
                                %strong Modulo:
                                = module_name[key.first]['name'].pluralize
                              %h5
                                %strong Acción:
                                = t("keppler.permissions.#{action}").camelize
                              %hr
                              %h5= t("keppler.permissions.descriptions.#{action}")

:scss
  .no-visible {
    display: none !important;
  }

app/views/admin/permissions/create.js.erb
$("#switch-container-<%= @module.split('::').join('') %>").html("<%= j render 'admin/permissions/switch', role: @role, module_name: @module.split('::').join(''), actions: @actions %>");
$("#switch-<%= @module.split('::').join('') %>-<%= @action %>").toggleClass('active');

app/views/admin/permissions/show.js.erb
$('#description-list').find('div').addClass('no-visible')
$("#description-<%= @module.split('::').join('') %>-<%= @action %>").toggleClass('no-visible');

app/views/admin/permissions/toggle_permissions.js.erb
$("#all-<%= @module.split('::').join('') %>").toggleClass('active');
// $("#switch-container-<%= @module.split('::').join('') %>").html("<%= j render 'admin/permissions/switch', role: @role, module_name: @module.split('::').join(''), actions: @actions %>");

<%- @actions.each do |action| %>
  $("#switch-<%= @module.split('::').join('') %>-<%= action %>").toggleClass('active');
<%- end %>