rockets/keppler_frontend/config/routes.rb
KepplerFrontend::Engine.routes.draw do
  root to: 'app/frontend#keppler', as: :keppler
  namespace :admin do
    scope :frontend, as: :frontend do
      resources :parameters do
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: 'clone'
        post '/sort', action: :sort, on: :collection
        post '/upload', action: 'upload', as: 'upload'
        get '/download', action: 'download', as: 'download'
        get(
          '/reload',
          action: :reload,
          on: :collection,
        )
        delete(
          '/destroy_multiple',
          action: :destroy_multiple,
          on: :collection,
          as: :destroy_multiple
        )
      end

      resources :functions do
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: 'clone'
        post '/sort', action: :sort, on: :collection
        post '/upload', action: 'upload', as: 'upload'
        get '/download', action: 'download', as: 'download'
        get '/editor', action: 'editor'
        post '/editor/save', action: 'editor_save'
        delete '/destroy_param/:param_id', action: :destroy_param, as: :destroy_param
        get(
          '/reload',
          action: :reload,
          on: :collection,
        )
        delete(
          '/destroy_multiple',
          action: :destroy_multiple,
          on: :collection,
          as: :destroy_multiple
        )
      end

      resources :callback_functions do
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: 'clone'
        post '/sort', action: :sort, on: :collection
        post '/upload', action: 'upload', as: 'upload'
        get '/download', action: 'download', as: 'download'
        get '/editor', action: 'editor'
        post '/editor/save', action: 'editor_save'
        get(
          '/reload',
          action: :reload,
          on: :collection,
        )
        delete(
          '/destroy_multiple',
          action: :destroy_multiple,
          on: :collection,
          as: :destroy_multiple
        )
      end

      resources :partials do
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: 'clone'
        post '/sort', action: :sort, on: :collection
        post '/upload', action: 'upload', as: 'upload'
        post '/editor/save', action: 'editor_save'
        get '/download', action: 'download', as: 'download'
        get(
          '/reload',
          action: :reload,
          on: :collection,
        )
        delete(
          '/destroy_multiple',
          action: :destroy_multiple,
          on: :collection,
          as: :destroy_multiple
        )
      end

      resources :themes do
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: 'clone'
        post '/sort', action: :sort, on: :collection
        post '/upload', action: 'upload', as: 'upload'
        get '/download', action: 'download', as: 'download'
        get '/show_covers', action: 'show_covers', as: 'show_covers'
        get '/editor', action: 'editor'
        post '/editor/save', action: 'editor_save'
        get(
          '/reload',
          action: :reload,
          on: :collection,
        )
        delete(
          '/destroy_multiple',
          action: :destroy_multiple,
          on: :collection,
          as: :destroy_multiple
        )
      end

      get '/assets', to: 'multimedia#index', as: 'multimedia'
      post '/assets/upload', to: 'multimedia#upload', as: 'upload_multimedia'
      get '/assets/upload', to: 'multimedia#upload', as: 'show_upload_multimedia'
      delete '/assets/:search/:fileformat', to: 'multimedia#destroy', as: 'destroy_multimedia'
      get '/assets/:search/:fileformat', to: 'multimedia#destroy', as: 'show_destroy_multimedia'

      resources :views do
        delete '/destroy_callback/:view_callback_id', action: :destroy_callback, as: :destroy_callback
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: 'clone'
        get '/editor', action: 'editor'
        post '/editor/save', action: 'editor_save'
        post '/live_editor/save', action: 'live_editor_save'
        post '/sort', action: :sort, on: :collection
        post '/select_theme_view/:theme_view', action: 'select_theme_view', as: :select_theme

        get(
          '/reload',
          action: :reload,
          on: :collection,
        )
        delete(
          '/destroy_multiple',
          action: :destroy_multiple,
          on: :collection,
          as: :destroy_multiple
        )
      end

    end
  end
end

rockets/keppler_frontend/app/models/keppler_frontend/parameter.rb
# Parameter Model
module KepplerFrontend
  class Parameter < ActiveRecord::Base
    include ActivityHistory
    include CloneRecord
    require 'csv'
    acts_as_list
    belongs_to :function
    # Fields for the search form in the navbar

    include KepplerFrontend::Concerns::StringActions

    validates_presence_of :name
    before_validation :without_special_characters

    def self.search_field
      fields = ["name", "position", "deleted_at"]
      build_query(fields, :or, :cont)
    end

    def self.upload(file)
      CSV.foreach(file.path, headers: true) do |row|
        begin
          self.create! row.to_hash
        rescue => err
        end
      end
    end

    def self.sorter(params)
      params.each_with_index do |id, idx|
        self.find(id).update(position: idx.to_i+1)
      end
    end

    # Funcion para armar el query de ransack
    def self.build_query(fields, operator, conf)
      query = fields.join("_#{operator}_")
      query << "_#{conf}"
      query.to_sym
    end
  end
end

rockets/keppler_frontend/app/controllers/keppler_frontend/admin/parameters_controller.rb
require_dependency "keppler_frontend/application_controller"
module KepplerFrontend
  module Admin
    # ParametersController
    class ParametersController < ::Admin::AdminController
      layout 'keppler_frontend/admin/layouts/application'
      before_action :set_parameter, only: [:show, :edit, :update, :destroy]
      before_action :show_history, only: [:index]
      before_action :set_attachments
      before_action :authorization
      # include KepplerFrontend::Concerns::Commons
      # include KepplerFrontend::Concerns::History
      # include KepplerFrontend::Concerns::DestroyMultiple


      # GET /parameters
      def index
        @q = Parameter.ransack(params[:q])
        parameters = @q.result(distinct: true)
        @objects = parameters.page(@current_page).order(position: :asc)
        @total = parameters.size
        @parameters = @objects.all
        if !@objects.first_page? && @objects.size.zero?
          redirect_to parameters_path(page: @current_page.to_i.pred, search: @query)
        end
        respond_to do |format|
          format.html
          format.xls { send_data(@parameters.to_xls) }
          format.json { render :json => @objects }
        end
      end

      # GET /parameters/1
      def show
      end

      # GET /parameters/new
      def new
        @parameter = Parameter.new
      end

      # GET /parameters/1/edit
      def edit
      end

      # POST /parameters
      def create
        @parameter = Parameter.new(parameter_params)

        if @parameter.save
          redirect(@parameter, params)
        else
          render :new
        end
      end

      # PATCH/PUT /parameters/1
      def update
        if @parameter.update(parameter_params)
          redirect(@parameter, params)
        else
          render :edit
        end
      end

      def clone
        @parameter = Parameter.clone_record params[:parameter_id]

        if @parameter.save
          redirect_to admin_frontend_parameters_path
        else
          render :new
        end
      end

      # DELETE /parameters/1
      def destroy
        @parameter.destroy
        redirect_to admin_frontend_parameters_path, notice: actions_messages(@parameter)
      end

      def destroy_multiple
        Parameter.destroy redefine_ids(params[:multiple_ids])
        redirect_to(
          admin_parameters_path(page: @current_page, search: @query),
          notice: actions_messages(Parameter.new)
        )
      end

      def upload
        Parameter.upload(params[:file])
        redirect_to(
          admin_parameters_path(page: @current_page, search: @query),
          notice: actions_messages(Parameter.new)
        )
      end

      def download
        @parameters = Parameter.all
        respond_to do |format|
          format.html
          format.xls { send_data(@parameters.to_xls) }
          format.json { render json: @parameters }
        end
      end

      def reload
        @q = Parameter.ransack(params[:q])
        parameters = @q.result(distinct: true)
        @objects = parameters.page(@current_page).order(position: :desc)
      end

      def sort
        Parameter.sorter(params[:row])
        @q = Parameter.ransack(params[:q])
        parameters = @q.result(distinct: true)
        @objects = parameters.page(@current_page)
        render :index
      end

      private

      def authorization
        authorize Parameter
      end

      def set_attachments
        @attachments = ['logo', 'brand', 'photo', 'avatar', 'cover', 'image',
                        'picture', 'banner', 'attachment', 'pic', 'file']
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_parameter
        @parameter = Parameter.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def parameter_params
        params.require(:parameter).permit(:name, :position, :deleted_at)
      end

      def show_history
        get_history(Parameter)
      end

      def get_history(model)
        @activities = PublicActivity::Activity.where(
          trackable_type: model.to_s
        ).order('created_at desc').limit(50)
      end

      # Get submit key to redirect, only [:create, :update]
      def redirect(object, commit)
        if commit.key?('_save')
          redirect_to([:admin, :frontend, object], notice: actions_messages(object))
        elsif commit.key?('_add_other')
          redirect_to(
            send("new_admin_frontend_#{underscore(object)}_path"),
            notice: actions_messages(object)
          )
        end
      end
    end
  end
end

rockets/keppler_frontend/app/helpers/keppler_frontend/parameters_helper.rb
module KepplerFrontend
  module ParametersHelper
  end
end

rockets/keppler_frontend/app/views/keppler_frontend/admin/parameters/_description.html.haml
%aside.control-sidebar.control-sidebar-light
  .tab-content
    %p.control-sidebar-heading
      = @activities.empty? ? t('keppler.messages.no_events') : t("keppler.titles.history")
    %ul.timeline
      - @activities.each do |activity|
        - if activity.trackable_type.eql? "Session"
          %li
            = render partial: "public_activity/session/#{activity.key.split(".").second}", locals: { activity: activity, method: "id" }
        - else
          %li
            = render partial: "public_activity/layout/#{activity.key.split(".").second}", locals: { activity: activity, method: "id" }
.control-sidebar-bg

rockets/keppler_frontend/app/views/keppler_frontend/admin/parameters/_form.html.haml
= simple_form_for [:admin, :frontend, @parameter] do |f|
  .container
    .row
      .col-lg-2
        = link_to admin_frontend_parameters_path, "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
          .arrow-back.btn.btn-default
            %i.fa.fa-angle-left
            = t('keppler.actions.back')

    .row
      .col-lg-12
        .box.slice-box
          .box-header.with-border
            %h3.box-title= t("keppler.modules.#{action_name.underscore}")
            .box-tools.pull-right
              %a.btn.btn-box-tool{"data-widget" => "collapse", :type => "button"}
                %i.fa.fa-minus
          .box-body
            %table.table.table-bordered
              %tbody
                .form-padding
                  .col-xs-12
                    = f.input :name
                  .col-xs-12
                    = f.input :position, as: :hidden
                  .col-xs-12
                    = f.input :deleted_at, as: :hidden
                  .col-xs-12
                    .pull-right
                      = f.button :submit, t('keppler.actions.save'), name: '_save', class: 'btn-primary'
                      = f.button :submit, t('keppler.actions.save_and_add_another'), name: '_add_other'

rockets/keppler_frontend/app/views/keppler_frontend/admin/parameters/_listing.html.haml
- objects.each do |parameter|
  %tr{ id: "row-#{parameter.id}" }
    %td.item-check{ style: 'width: 10%' }
      - if can?(KepplerFrontend::Parameter).destroy_multiple?
        .checkbox
          %label{ for: "checkbox-#{parameter.id}" }
            %input{ type: 'checkbox', id: "checkbox-#{parameter.id}", 'checklist-model' => 'check', 'checklist-value' => "#{parameter.id}", '@click' => "listDelete(#{parameter.id})"}
            %span.cr
              %i.cr-icon.glyphicon.glyphicon-ok
    %td.hidden-xs
      = link_to admin_frontend_parameter_path(parameter, search: @query), remote: true, class: 'show-row' do
        %span
          = parameter.name
    %td{ style: 'width: 15px;padding-right:15px;' }
      %a.action-btn.pull-right{:id => "menu-#{parameter.id}", 'aria-expanded': 'false', 'aria-haspopup': 'true', 'data-toggle': 'dropdown' }
        %i.icon-options-vertical
      %ul.actions.dropdown-menu{ 'aria-labelledby': "menu-#{parameter.id}" }
        - if can?(KepplerFrontend::Parameter).index?
          %li
            = link_to admin_frontend_parameter_path(parameter), class: 'new-menu', title: t('keppler.actions.show') do
              %i.icon-eye
              = t('keppler.actions.show')
        - if can?(KepplerFrontend::Parameter).update?
          %li
            = link_to edit_admin_frontend_parameter_path(parameter), class: 'new-menu', title: t('keppler.actions.edit') do
              %i.icon-pencil
              = t('keppler.actions.edit')
        - if can?(KepplerFrontend::Parameter).clone?
          %li
            = link_to admin_frontend_parameter_clone_path(parameter), class: 'new-menu', title: t('keppler.actions.clone') do
              %i.icon-docs
              = t('keppler.actions.clone')
        - if can?(KepplerFrontend::Parameter).destroy?
          %li
            = link_to admin_frontend_parameter_path(parameter), class: 'new-menu', title: t('keppler.actions.delete'), method: :delete, data: { confirm: t('keppler.messages.data_confirm') } do
              %i.icon-trash
              = t('keppler.actions.delete')

    %td{ style: 'width: 5%;' }
      %a.drop{ href: '#' }
        %i.icon-cursor-move

rockets/keppler_frontend/app/views/keppler_frontend/admin/parameters/edit.html.haml
= render 'form'

rockets/keppler_frontend/app/views/keppler_frontend/admin/parameters/index.html.haml
#index-container{ :controller => "parameters" }
  .container
    .row
      .listing.col-lg-12.col-xs-12
        %section.content-header.index-header
          %h1{ style: 'display: inline-block' }
            = t("keppler.modules.#{controller_path.underscore}")
          = entries(@total, @objects)
          .toolbar
            - if can?(KepplerFrontend::Parameter).download?
              .toolbar-item
                = link_to admin_frontend_parameter_download_path(KepplerFrontend::Parameter, :format => :xls), class: "tool-btn", title: t('keppler.actions.download_records') do
                  %i.icon-cloud-download
            - if can?(KepplerFrontend::Parameter).upload?
              .toolbar-item
                = link_to "", class: "tool-btn", title: t('keppler.actions.upload_records'), id: "parameter" do
                  %i.icon-cloud-upload
            .toolbar-item
              = link_to reload_admin_frontend_parameters_path, class: "tool-btn", remote: true do
                %i.icon-reload
            - if can?(KepplerFrontend::Parameter).destroy_multiple?
              .toolbar-item
                .checkbox
                  %label{ for: 'checkbox-all' }
                    %input{ type: 'checkbox', id: 'checkbox-all', ':disabled' => 'checkItems ? disabled : ""', '@click' => 'selectAll()' }
                    %span.cr
                      %i.cr-icon.glyphicon.glyphicon-ok
            .toolbar-item
              %a.tool-btn{"data-confirm" => "¿Estás seguro?", "data-method" => "delete", "v-bind:href" => "link", :rel => "nofollow", ":class" => "{disabled: !checks}" }
                %i.icon-trash
          .hide
            = form_tag admin_frontend_parameter_upload_path(@objects), id: "upload_form_parameters", multipart: true, method: :post do
              = file_field_tag :file, id: "upload_file_parameter"
          %ol.breadcrumb
            %li
              %a{ href: '#' }
                %i.icon-directions
                = t("keppler.modules.#{action_name.underscore}")

        .box.slice-box
          .box-body.no-padding

            %table.table
              %thead
                - if @objects.size.zero?
                  %tr
                    %th{style: 'text-align: center;'}
                      %h6= t('keppler.messages.not_found_records', model:  t("keppler.models.pluralize.parameters"))
                - else
                  %tr
                    %th
                    %th.hidden-xs= t('activerecord.attributes.name')
                    %th.center Menu
                    %th
              %tbody#objects-container
                = render 'admin/layouts/listing_preloader'
                = render 'listing', objects: @objects
        %center#paginator-module
          = paginate @objects, window: 1
  %aside.control-sidebar
    = render "description"

  .mixed-btn
    - if can?(KepplerFrontend::Parameter).create?
      = link_to new_admin_frontend_parameter_path, class: "btn-float" do
        +

:javascript
  $(document).ready(function(){
    $('#parameter').click(function() {
      $('#upload_file_parameter').click()
      $('#upload_file_parameter').change(function() {
        $('.waiting').css('display', 'block')
        $('#upload_form_parameter').submit()
      })
    });

    renderImg();
  });

rockets/keppler_frontend/app/views/keppler_frontend/admin/parameters/new.html.haml
= render 'form'

rockets/keppler_frontend/app/views/keppler_frontend/admin/parameters/reload.js.haml
$('#objects-container').html("#{j render 'listing', objects: @objects}");
$('#objects-container').css('opacity', '0');
$('#spinner2').css('display', 'block');
var request = $.ajax({url: "/admin/parameters", method: "get", dataType: "html"});
request.done(function(msg){$('#spinner2').css('display', 'none');$('#objects-container').css('opacity', '1');});

rockets/keppler_frontend/app/views/keppler_frontend/admin/parameters/show.html.haml
.container
  .row
    .col-lg-2
      = link_to admin_frontend_parameters_path, "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
        .arrow-back.btn.btn-default
          %i.fa.fa-angle-left
          = t('keppler.actions.back')

  .show-section
    .row
      .col-lg-12
        .box.slice-box
          .box-header.with-border
            %h3.box-title= t("keppler.modules.#{controller_path.underscore}")
            .box-tools.pull-right
              - if can?(KepplerFrontend::Parameter).update?
                = link_to edit_admin_frontend_parameter_path(@parameter), class: "btn btn-box-tool", title: "#{t('keppler.actions.edit') }" do
                  %i.icon-pencil
              - if can?(KepplerFrontend::Parameter).destroy?
                = link_to admin_frontend_parameter_path(@parameter), class: "btn btn-box-tool", title: "#{t('keppler.actions.delete')}", method: :delete, data: { confirm: t('keppler.messages.data_confirm') } do
                  %i.icon-trash
          .box-body.box-body-no-padding
            %table.table.table-striped
              %tbody
                - @parameter.as_json(only: ["name", "position", "deleted_at"]).each do |attribute, value|
                  - unless attribute.eql?('position') || attribute.eql?('deleted_at')
                    %tr.list-row
                      %th.display-label= t("activerecord.attributes.#{attribute}")
                      %td.display-value.fs-body-1.tc-black-2
                        - if @attachments.include?(attribute)
                          = image_tag value.url unless value.url.blank?
                        - else
                          = value.blank? ? '-----------' : value